#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export THETAEVOLVE_MODEL_NAME="Qwen3-4B-Thinking-2507"
export THETAEVOLVE_MODEL_ARGS_SCRIPT="scripts/models/qwen3-4B-Thinking-2507.sh"

export THETAEVOLVE_NUM_GPUS_PER_NODE="${THETAEVOLVE_NUM_GPUS_PER_NODE:-16}"
export THETAEVOLVE_TRAIN_GPUS_PER_NODE="${THETAEVOLVE_TRAIN_GPUS_PER_NODE:-4}"
export THETAEVOLVE_ROLLOUT_NUM_GPUS="${THETAEVOLVE_ROLLOUT_NUM_GPUS:-4}"
export THETAEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE="${THETAEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE:-2}"
export THETAEVOLVE_TENSOR_MODEL_PARALLEL_SIZE="${THETAEVOLVE_TENSOR_MODEL_PARALLEL_SIZE:-4}"
export THETAEVOLVE_CONTEXT_PARALLEL_SIZE="${THETAEVOLVE_CONTEXT_PARALLEL_SIZE:-1}"
export THETAEVOLVE_TRAIN_SEQ_LENGTH="${THETAEVOLVE_TRAIN_SEQ_LENGTH:-8192}"
export THETAEVOLVE_MAX_POSITION_EMBEDDINGS="${THETAEVOLVE_MAX_POSITION_EMBEDDINGS:-${THETAEVOLVE_TRAIN_SEQ_LENGTH}}"
export THETAEVOLVE_MAX_TOKENS_PER_GPU="${THETAEVOLVE_MAX_TOKENS_PER_GPU:-4096}"
export THETAEVOLVE_ROLLOUT_MAX_RESPONSE_LEN="${THETAEVOLVE_ROLLOUT_MAX_RESPONSE_LEN:-32768}"
export THETAEVOLVE_ROLLOUT_MAX_CONTEXT_LEN="${THETAEVOLVE_ROLLOUT_MAX_CONTEXT_LEN:-65536}"
export THETAEVOLVE_ROLLOUT_MAX_PROMPT_LEN="${THETAEVOLVE_ROLLOUT_MAX_PROMPT_LEN:-24576}"
export THETAEVOLVE_SGLANG_MEM_FRACTION_STATIC="${THETAEVOLVE_SGLANG_MEM_FRACTION_STATIC:-0.55}"

bash "${ROOT_DIR}/common_thetaevolve.sh" "$@"
