#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export THETAEVOLVE_MODEL_NAME="DeepSeek-R1-0528-Qwen3-8B"
export THETAEVOLVE_MODEL_ARGS_SCRIPT="scripts/models/qwen3-8B.sh"

export THETAEVOLVE_NUM_GPUS_PER_NODE="${THETAEVOLVE_NUM_GPUS_PER_NODE:-16}"
export THETAEVOLVE_TRAIN_GPUS_PER_NODE="${THETAEVOLVE_TRAIN_GPUS_PER_NODE:-4}"
export THETAEVOLVE_ROLLOUT_NUM_GPUS="${THETAEVOLVE_ROLLOUT_NUM_GPUS:-4}"
export THETAEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE="${THETAEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE:-4}"
export THETAEVOLVE_TENSOR_MODEL_PARALLEL_SIZE="${THETAEVOLVE_TENSOR_MODEL_PARALLEL_SIZE:-4}"
export THETAEVOLVE_CONTEXT_PARALLEL_SIZE="${THETAEVOLVE_CONTEXT_PARALLEL_SIZE:-1}"
export THETAEVOLVE_SGLANG_MEM_FRACTION_STATIC="${THETAEVOLVE_SGLANG_MEM_FRACTION_STATIC:-0.4}"

bash "${ROOT_DIR}/common_thetaevolve.sh" "$@"
