#!/bin/bash
# Thin ThetaEvolve/OpenEvolve launcher for KuaRec on DeepSeek-R1-0528-Qwen3-8B.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export TASK="kuairec"
export SMALL_MODEL_NAME="${SMALL_MODEL_NAME:-dpsk_distill_qwen3_8b}"

# KuaRec prompts include the full fixed training script. On 40GB A100s, the
# 8B model OOMs with the generic 4-GPU train split and 16k rollout responses
# while recomputing policy log-probs over prompt+response.
export THETAEVOLVE_TRAIN_GPUS_PER_NODE="${THETAEVOLVE_TRAIN_GPUS_PER_NODE:-8}"
export THETAEVOLVE_CONTEXT_PARALLEL_SIZE="${THETAEVOLVE_CONTEXT_PARALLEL_SIZE:-2}"
export THETAEVOLVE_EVAL_GPU_IDS="${THETAEVOLVE_EVAL_GPU_IDS:-12,13,14,15}"
export THETAEVOLVE_MAX_CONCURRENT_EVALS="${THETAEVOLVE_MAX_CONCURRENT_EVALS:-4}"

export THETAEVOLVE_TRAIN_SEQ_LENGTH="${THETAEVOLVE_TRAIN_SEQ_LENGTH:-2048}"
export THETAEVOLVE_MAX_POSITION_EMBEDDINGS="${THETAEVOLVE_MAX_POSITION_EMBEDDINGS:-2048}"
export THETAEVOLVE_MAX_TOKENS_PER_GPU="${THETAEVOLVE_MAX_TOKENS_PER_GPU:-1024}"
export THETAEVOLVE_LOG_PROBS_MAX_TOKENS_PER_GPU="${THETAEVOLVE_LOG_PROBS_MAX_TOKENS_PER_GPU:-1024}"
export THETAEVOLVE_ROLLOUT_MAX_RESPONSE_LEN="${THETAEVOLVE_ROLLOUT_MAX_RESPONSE_LEN:-4096}"

# Keep the OpenEvolve prompt compact enough for policy training. The current
# program is still included; these only remove extra full-program history and
# evaluator artifacts that otherwise duplicate tens of KB per prompt.
export THETAEVOLVE_KUAIREC_LLM_MAX_TOKENS="${THETAEVOLVE_KUAIREC_LLM_MAX_TOKENS:-4096}"
export THETAEVOLVE_KUAIREC_PROMPT_NUM_TOP_PROGRAMS="${THETAEVOLVE_KUAIREC_PROMPT_NUM_TOP_PROGRAMS:-0}"
export THETAEVOLVE_KUAIREC_PROMPT_NUM_DIVERSE_PROGRAMS="${THETAEVOLVE_KUAIREC_PROMPT_NUM_DIVERSE_PROGRAMS:-0}"
export THETAEVOLVE_KUAIREC_PROMPT_NUM_INSPIRATION_PROGRAMS="${THETAEVOLVE_KUAIREC_PROMPT_NUM_INSPIRATION_PROGRAMS:-0}"
export THETAEVOLVE_KUAIREC_PROMPT_INCLUDE_ARTIFACTS="${THETAEVOLVE_KUAIREC_PROMPT_INCLUDE_ARTIFACTS:-false}"
export THETAEVOLVE_KUAIREC_PROMPT_MAX_ARTIFACT_BYTES="${THETAEVOLVE_KUAIREC_PROMPT_MAX_ARTIFACT_BYTES:-0}"

bash "${ROOT_DIR}/run_thetaevolve_task.sh"
