#!/bin/bash
# Thin launcher for the KuaRec/FuXi task on the 1.5B reasoning model.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export SMALL_MODEL_NAME="${SMALL_MODEL_NAME:-dpsk_prorl_v2_1.5b}"

# Recommended 16-GPU split for the smaller model:
#   - training: GPUs 0,1,2,3
#   - rollout:  GPUs 4,5,6,7
#   - eval:     GPUs 8,9,10,11,12,13,14,15
export PACEVOLVE_NUM_GPUS_PER_NODE="${PACEVOLVE_NUM_GPUS_PER_NODE:-16}"
export PACEVOLVE_TRAIN_GPUS_PER_NODE="${PACEVOLVE_TRAIN_GPUS_PER_NODE:-4}"
export PACEVOLVE_ROLLOUT_NUM_GPUS="${PACEVOLVE_ROLLOUT_NUM_GPUS:-4}"
export PACEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE="${PACEVOLVE_ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
export PACEVOLVE_EVAL_GPU_IDS="${PACEVOLVE_EVAL_GPU_IDS:-8,9,10,11,12,13,14,15}"
export PACEVOLVE_MAX_CONCURRENT_EVALS="${PACEVOLVE_MAX_CONCURRENT_EVALS:-8}"

export PACEVOLVE_TENSOR_MODEL_PARALLEL_SIZE="${PACEVOLVE_TENSOR_MODEL_PARALLEL_SIZE:-2}"
export PACEVOLVE_PIPELINE_MODEL_PARALLEL_SIZE="${PACEVOLVE_PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export PACEVOLVE_CONTEXT_PARALLEL_SIZE="${PACEVOLVE_CONTEXT_PARALLEL_SIZE:-2}"
export PACEVOLVE_EXPERT_MODEL_PARALLEL_SIZE="${PACEVOLVE_EXPERT_MODEL_PARALLEL_SIZE:-1}"
export PACEVOLVE_EXPERT_TENSOR_PARALLEL_SIZE="${PACEVOLVE_EXPERT_TENSOR_PARALLEL_SIZE:-1}"

export PACEVOLVE_TRAIN_SEQ_LENGTH="${PACEVOLVE_TRAIN_SEQ_LENGTH:-8192}"
export PACEVOLVE_MAX_POSITION_EMBEDDINGS="${PACEVOLVE_MAX_POSITION_EMBEDDINGS:-${PACEVOLVE_TRAIN_SEQ_LENGTH}}"
export PACEVOLVE_MAX_TOKENS_PER_GPU="${PACEVOLVE_MAX_TOKENS_PER_GPU:-4096}"
export PACEVOLVE_ROLLOUT_MAX_CONTEXT_LEN="${PACEVOLVE_ROLLOUT_MAX_CONTEXT_LEN:-32768}"
export PACEVOLVE_ROLLOUT_MAX_PROMPT_LEN="${PACEVOLVE_ROLLOUT_MAX_PROMPT_LEN:-24576}"
export PACEVOLVE_SGLANG_MEM_FRACTION_STATIC="${PACEVOLVE_SGLANG_MEM_FRACTION_STATIC:-0.65}"
export PACEVOLVE_SGLANG_SERVER_CONCURRENCY="${PACEVOLVE_SGLANG_SERVER_CONCURRENCY:-128}"

bash "${ROOT_DIR}/run_kuairec.sh"
